### ISSUE TITLE
Regarding the error message.

### ISSUE THREAD

**Issue by DhawalJethwani** [disconsis/comp-arch-lab#1]
Add this at the end of the code:

          jr    $ra

Also change the output register from $v0 to $v1. You won't get the error message.

**Comment by disconsis** [comment]
Good point regarding the jump.
Why exactly should the return value be into v1?

**Comment by DhawalJethwani** [comment]
I don't why but v0 is overwritten to a value 'a'.

**Comment by disconsis** [comment]
Probably the exit value from the outer function

**Comment by disconsis** [comment]
:+1: I'll change it

**Comment by DhawalJethwani** [comment]
Even I think that it is the return value from some other function. Cheers!

**Comment by disconsis** [comment]
For completion's sake: v0 has 10 at the end because exit is syscall 10. :neutral_face:
